# Generated by Django 3.2.12 on 2022-03-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_customer_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='phone_number',
        ),
    ]
